

app = "sec3fr"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]


[build.args]
  NEXT_PUBLIC_WALLET_CONNECT_PROJECT_ID="2e4a7b7cfb5bfc7d568289e0dbeda110"